# Generated by Django 5.0.14 on 2026-03-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_checklist_assignments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="executor",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Респондент",
                "verbose_name_plural": "Респонденты",
            },
        ),
        migrations.AlterField(
            model_name="audit",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audits",
                to="audits.executor",
                verbose_name="Респондент",
            ),
        ),
        migrations.AlterField(
            model_name="checklistassignment",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="audits.executor",
                verbose_name="Респондент",
            ),
        ),
        migrations.AlterField(
            model_name="executor",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Группа"),
        ),
    ]
